-- APLICAR QUEBRAS NOS REGISTROS EXISTENTES DE "TC CRANIO E ANGIO ARTERIAL E VENOSA CRANIO"

-- 1. Primeiro, criar os registros quebrados para cada registro original
INSERT INTO volumetria_mobilemed (
  "EMPRESA", "NOME_PACIENTE", "CODIGO_PACIENTE", "ESTUDO_DESCRICAO", 
  "ACCESSION_NUMBER", "MODALIDADE", "PRIORIDADE", "VALORES", "ESPECIALIDADE",
  "MEDICO", "DUPLICADO", "DATA_REALIZACAO", "HORA_REALIZACAO",
  "DATA_TRANSFERENCIA", "HORA_TRANSFERENCIA", "DATA_LAUDO", "HORA_LAUDO",
  "DATA_PRAZO", "HORA_PRAZO", "STATUS", "DATA_REASSINATURA",
  "HORA_REASSINATURA", "MEDICO_REASSINATURA", "SEGUNDA_ASSINATURA",
  "POSSUI_IMAGENS_CHAVE", "IMAGENS_CHAVES", "IMAGENS_CAPTURADAS",
  "CODIGO_INTERNO", "DIGITADOR", "COMPLEMENTAR", data_referencia,
  arquivo_fonte, lote_upload, periodo_referencia, "CATEGORIA",
  created_at, updated_at, tipo_faturamento, processamento_pendente
)
SELECT 
  vm."EMPRESA", vm."NOME_PACIENTE", vm."CODIGO_PACIENTE", 'TC CRANIO',
  vm."ACCESSION_NUMBER", vm."MODALIDADE", vm."PRIORIDADE", 1, vm."ESPECIALIDADE",
  vm."MEDICO", vm."DUPLICADO", vm."DATA_REALIZACAO", vm."HORA_REALIZACAO",
  vm."DATA_TRANSFERENCIA", vm."HORA_TRANSFERENCIA", vm."DATA_LAUDO", vm."HORA_LAUDO",
  vm."DATA_PRAZO", vm."HORA_PRAZO", vm."STATUS", vm."DATA_REASSINATURA",
  vm."HORA_REASSINATURA", vm."MEDICO_REASSINATURA", vm."SEGUNDA_ASSINATURA",
  vm."POSSUI_IMAGENS_CHAVE", vm."IMAGENS_CHAVES", vm."IMAGENS_CAPTURADAS",
  vm."CODIGO_INTERNO", vm."DIGITADOR", vm."COMPLEMENTAR", vm.data_referencia,
  vm.arquivo_fonte, vm.lote_upload, vm.periodo_referencia, COALESCE(vm."CATEGORIA", 'SC'),
  vm.created_at, now(), vm.tipo_faturamento, false
FROM volumetria_mobilemed vm
WHERE vm."ESTUDO_DESCRICAO" = 'TC CRANIO E ANGIO ARTERIAL E VENOSA CRANIO';

-- 2. Inserir ANGIOTC ARTERIAL CRANIO
INSERT INTO volumetria_mobilemed (
  "EMPRESA", "NOME_PACIENTE", "CODIGO_PACIENTE", "ESTUDO_DESCRICAO", 
  "ACCESSION_NUMBER", "MODALIDADE", "PRIORIDADE", "VALORES", "ESPECIALIDADE",
  "MEDICO", "DUPLICADO", "DATA_REALIZACAO", "HORA_REALIZACAO",
  "DATA_TRANSFERENCIA", "HORA_TRANSFERENCIA", "DATA_LAUDO", "HORA_LAUDO",
  "DATA_PRAZO", "HORA_PRAZO", "STATUS", "DATA_REASSINATURA",
  "HORA_REASSINATURA", "MEDICO_REASSINATURA", "SEGUNDA_ASSINATURA",
  "POSSUI_IMAGENS_CHAVE", "IMAGENS_CHAVES", "IMAGENS_CAPTURADAS",
  "CODIGO_INTERNO", "DIGITADOR", "COMPLEMENTAR", data_referencia,
  arquivo_fonte, lote_upload, periodo_referencia, "CATEGORIA",
  created_at, updated_at, tipo_faturamento, processamento_pendente
)
SELECT 
  vm."EMPRESA", vm."NOME_PACIENTE", vm."CODIGO_PACIENTE", 'ANGIOTC ARTERIAL CRANIO',
  vm."ACCESSION_NUMBER", vm."MODALIDADE", vm."PRIORIDADE", 1, vm."ESPECIALIDADE",
  vm."MEDICO", vm."DUPLICADO", vm."DATA_REALIZACAO", vm."HORA_REALIZACAO",
  vm."DATA_TRANSFERENCIA", vm."HORA_TRANSFERENCIA", vm."DATA_LAUDO", vm."HORA_LAUDO",
  vm."DATA_PRAZO", vm."HORA_PRAZO", vm."STATUS", vm."DATA_REASSINATURA",
  vm."HORA_REASSINATURA", vm."MEDICO_REASSINATURA", vm."SEGUNDA_ASSINATURA",
  vm."POSSUI_IMAGENS_CHAVE", vm."IMAGENS_CHAVES", vm."IMAGENS_CAPTURADAS",
  vm."CODIGO_INTERNO", vm."DIGITADOR", vm."COMPLEMENTAR", vm.data_referencia,
  vm.arquivo_fonte, vm.lote_upload, vm.periodo_referencia, 'ANGIO',
  vm.created_at, now(), vm.tipo_faturamento, false
FROM volumetria_mobilemed vm
WHERE vm."ESTUDO_DESCRICAO" = 'TC CRANIO E ANGIO ARTERIAL E VENOSA CRANIO';

-- 3. Inserir ANGIOTC VENOSA CRANIO
INSERT INTO volumetria_mobilemed (
  "EMPRESA", "NOME_PACIENTE", "CODIGO_PACIENTE", "ESTUDO_DESCRICAO", 
  "ACCESSION_NUMBER", "MODALIDADE", "PRIORIDADE", "VALORES", "ESPECIALIDADE",
  "MEDICO", "DUPLICADO", "DATA_REALIZACAO", "HORA_REALIZACAO",
  "DATA_TRANSFERENCIA", "HORA_TRANSFERENCIA", "DATA_LAUDO", "HORA_LAUDO",
  "DATA_PRAZO", "HORA_PRAZO", "STATUS", "DATA_REASSINATURA",
  "HORA_REASSINATURA", "MEDICO_REASSINATURA", "SEGUNDA_ASSINATURA",
  "POSSUI_IMAGENS_CHAVE", "IMAGENS_CHAVES", "IMAGENS_CAPTURADAS",
  "CODIGO_INTERNO", "DIGITADOR", "COMPLEMENTAR", data_referencia,
  arquivo_fonte, lote_upload, periodo_referencia, "CATEGORIA",
  created_at, updated_at, tipo_faturamento, processamento_pendente
)
SELECT 
  vm."EMPRESA", vm."NOME_PACIENTE", vm."CODIGO_PACIENTE", 'ANGIOTC VENOSA CRANIO',
  vm."ACCESSION_NUMBER", vm."MODALIDADE", vm."PRIORIDADE", 1, vm."ESPECIALIDADE",
  vm."MEDICO", vm."DUPLICADO", vm."DATA_REALIZACAO", vm."HORA_REALIZACAO",
  vm."DATA_TRANSFERENCIA", vm."HORA_TRANSFERENCIA", vm."DATA_LAUDO", vm."HORA_LAUDO",
  vm."DATA_PRAZO", vm."HORA_PRAZO", vm."STATUS", vm."DATA_REASSINATURA",
  vm."HORA_REASSINATURA", vm."MEDICO_REASSINATURA", vm."SEGUNDA_ASSINATURA",
  vm."POSSUI_IMAGENS_CHAVE", vm."IMAGENS_CHAVES", vm."IMAGENS_CAPTURADAS",
  vm."CODIGO_INTERNO", vm."DIGITADOR", vm."COMPLEMENTAR", vm.data_referencia,
  vm.arquivo_fonte, vm.lote_upload, vm.periodo_referencia, 'ANGIO',
  vm.created_at, now(), vm.tipo_faturamento, false
FROM volumetria_mobilemed vm
WHERE vm."ESTUDO_DESCRICAO" = 'TC CRANIO E ANGIO ARTERIAL E VENOSA CRANIO';

-- 4. AGORA DELETAR TODOS OS REGISTROS ORIGINAIS
DELETE FROM volumetria_mobilemed 
WHERE "ESTUDO_DESCRICAO" = 'TC CRANIO E ANGIO ARTERIAL E VENOSA CRANIO';